### PR TITLE
Migrate to Java 8

### PR DESCRIPTION
**Pull request by clementdenis**
- Use JDK's Stream / Optional instead of Guava classes
- Lambdaify code
- Remove finals where unnecessary

### CODE REVIEW

**Review by llbrt — COMMENTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/8)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @alarribeau, @clementdenis, and @llbrt)

___
*[pom.xml, line 52 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/8#-LhoIHaf5HLAX3yfHiee:-LhoIHag-SLDSqe5cHFA:b-kg9thn) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/4ce124d2dc96851c538dfdea856b0a10f9092481/pom.xml#L52)):*
> ```XML
>             <groupId>com.google.guava</groupId>
>             <artifactId>guava</artifactId>
>             <version>27.1-jre</version>
> ```

Shouldn't we keep the same version as for Cloud Endpoints (20.0)?

**Review by alarribeau — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/8)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/8#-:-LiDXjxl9vMKPYrTGxzO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by llbrt — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/8#-:-LimiQDJE8sqXSsrmHX4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by llbrt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
