### PR TITLE
#2 Wildcards handling improvements

### PR DESCRIPTION
**Pull request by alarribeau**
- disregard terminal wildcards on filtering
- add expression validation on dead branches

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4)

### CODE REVIEW

**Review by RaHery — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @alarribeau, @clementdenis, @llbrt, and @RaHery)

___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 39 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFIqDq5QlkmNPOMXrq:-LaFIqDq5QlkmNPOMXrr:bn03yj) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L39)):*
> ```Java
> 	
> 	private final String fieldExpression;
> 	private final Parser parser;
> ```

At first sight, it's rather puzzling to have a parser as a part of an expression. Maybe you can use a parser to create an expression: keep as field the result of parsing (remove `parser` as field, and create a new field of type `FluentIterable<ImmutableList<String>>` - the result of the parsing)
___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 55 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFKxrg39rE6eaIGQeB:-LaFKxrg39rE6eaIGQeC:blcb4cv) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L55)):*
> ```Java
> 	}
> 	
> 	public FluentIterable<FieldsExpressionNode> asPathNodes() {
> ```

This method is only used for the validation (for the actual filtering, the other method `getFilterTree(..)` is used. Keep this method private.
___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 72 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFPbii3l-7wofIS8V4:-LaFPbij3dYwQeqmHXns:bcttoad) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L72)):*
> ```Java
> 			builder.getOrAddBranch(livePath);
> 		}
> 		return new FieldsExpressionTree(builder.getNode());
> ```

This expression tree is immutable. I would created it in the constructor, and keep a final immutable field of type `FieldsExpressionTree`. 
___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 105 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFQ9Oa8taq2ILbxfJO:-LaFQ9Oa8taq2ILbxfJP:b-tacmyu) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L105)):*
> ```Java
> 	}
> 	
> 	
> ```

Extra blank line :)

**Review by RaHery — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4)* status: all files reviewed, 4 unresolved discussions (waiting on @alarribeau, @clementdenis, and @llbrt)

**Review by alarribeau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4)* status: all files reviewed, 2 unresolved discussions (waiting on @alarribeau, @clementdenis, @llbrt, and @RaHery)

___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 39 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFIqDq5QlkmNPOMXrq:-LaPiMzJ1UY3iTZ_lNm-:bu5s8uq) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L39)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

At first sight, it's rather puzzling to have a parser as a part of an expression. Maybe you can use a parser to create an expression: keep as field the result of parsing (remove `parser` as field, and create a new field of type `FluentIterable<ImmutableList<String>>` - the result of the parsing)
</blockquote></details>

You're absolutely right : I refactored the Parser just for that reason and I forgot the end goal :)

(In an intermediary step I had 2 parser outputs and one was only used when validating this is why I kept the parser. And since it puzzled me, I moved some logic from the parser to the field expression which make it possible to get ride of this parser instance.)
___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 55 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFKxrg39rE6eaIGQeB:-LaPkFVz489uEKtymJv6:b-896fix) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L55)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

This method is only used for the validation (for the actual filtering, the other method `getFilterTree(..)` is used. Keep this method private.
</blockquote></details>

Done.
___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 72 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFPbii3l-7wofIS8V4:-LaPk_JNB-BBt-LemBtQ:bxz33lc) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L72)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

This expression tree is immutable. I would created it in the constructor, and keep a final immutable field of type `FieldsExpressionTree`. 
</blockquote></details>

I didn't wanted to eager build it because it may not be used (if the FieldsExpression is used only for validation). 
Now, it would be redundant with the (new) fieldsExpressionPaths...
___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 105 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFQ9Oa8taq2ILbxfJO:-LaPlOEW-z6-FlBYE71C:b-896fja) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L105)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Extra blank line :)
</blockquote></details>

Done!

**Review by alarribeau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @clementdenis, @llbrt, and @RaHery)

___
*[src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java, line 39 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-LaFIqDq5QlkmNPOMXrq:-LaQFH5i6wIcboDkYJUQ:b-896fix) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/e41bc8b29287e884b2f601734a44de34520dfd4e/src/main/java/com/aodocs/partialresponse/fieldsexpression/FieldsExpression.java#L39)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

You're absolutely right : I refactored the Parser just for that reason and I forgot the end goal :)

(In an intermediary step I had 2 parser outputs and one was only used when validating this is why I kept the parser. And since it puzzled me, I moved some logic from the parser to the field expression which make it possible to get ride of this parser instance.)
</blockquote></details>

Done.

**Review by RaHery — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4#-:-LaQwEsi4i6R6QN0m66v:bnfp4nl)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @clementdenis, @llbrt, and @RaHery)

**Review by RaHery — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clementdenis and @llbrt)

**Pull request merged**
