### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by clementdenis**

### CODE REVIEW

**Comment by clementdenis** [comment]
Should wait for Endpoints 2.4.0 before merging

**Review by RaHery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12#-:-Lsugkof1zgAEq4pRlV5:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alarribeau)

**Review by RaHery — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)

**Review by alarribeau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[pom.xml, line 38 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12#-Lsuwy-B5uUC2-Ei1R0U:-Lsuwy-B5uUC2-Ei1R0V:ba6oir1) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/ef0d4ad2e38bcf7c6210cb0169728392f3e65ae4/pom.xml#L38)):*
> ```XML
>         <repackagedDir>endpoints.repackaged</repackagedDir>
> 
>         <endpoints-framework.version>2.3.3</endpoints-framework.version>
> ```

Shouldn't we depend on the latest release (2.4.0) instead ? 
@rahery  ?

**Review by RaHery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau)

___
*[pom.xml, line 38 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12#-Lsuwy-B5uUC2-Ei1R0U:-LsuyaX_89Mu1A7XFUMa:brxin9w) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/ef0d4ad2e38bcf7c6210cb0169728392f3e65ae4/pom.xml#L38)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Shouldn't we depend on the latest release (2.4.0) instead ? 
@rahery  ?
</blockquote></details>

Correct.
I just thought i'd merged this (very) old pr just for the history, and create another specific for the upgrade to 2.4.0 ... but ok, let's do both things in one shot.

**Review by alarribeau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[pom.xml, line 38 at r1](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12#-Lsuwy-B5uUC2-Ei1R0U:-LsvDpLI-wOWfLrCm8E1:b-8fx2u7) ([raw file](https://github.com/aodocs/endpoints-partialresponse/blob/ef0d4ad2e38bcf7c6210cb0169728392f3e65ae4/pom.xml#L38)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Correct.
I just thought i'd merged this (very) old pr just for the history, and create another specific for the upgrade to 2.4.0 ... but ok, let's do both things in one shot.
</blockquote></details>

:+1:

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-partialresponse/12#-:-LsvE1722IpT0FPHwaxg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
